### ISSUE TITLE
DOM types are not linked

### ISSUE THREAD

**Issue by oliversalzburg** [Gerrit0/typedoc-plugin-mdn-links#13]
I have a property in my code:

```ts
readonly context: CanvasRenderingContext2D;
```

This property does not have its type linked in the resulting TypeDoc output. Seemingly, the issue originates from:

https://github.com/Gerrit0/typedoc-plugin-mdn-links/blob/36e27711ebe8bdfbfe9494fb6abb150e40af236d/src/index.ts#L55-L57

In my scenario, the `moduleSource` is `@types/web`, so the linking is skipped. Is this a configuration issue on my part?

**Comment by oliversalzburg** [comment]
FWIW, if I add `(declaration.moduleSource && declaration.moduleSource.startsWith("@types/"))` into the mix, I get the result I expect.

**Comment by Gerrit0** [comment]
This should be fixed in the latest version now

**Comment by oliversalzburg** [comment]
I feel like something is wrong with the package: https://github.com/oliversalzburg/js-utils/actions/runs/6914103613/job/18811616752?pr=21

**Comment by Gerrit0** [comment]
Fixed in 3.1.3

**Comment by oliversalzburg** [comment]
Looks great. Problem fixed 😄
