### ISSUE TITLE
Insufficient information on `additionalModuleSources` option

### ISSUE THREAD

**Issue by XieWren** [Gerrit0/typedoc-plugin-mdn-links#20]
On the README, `additionalModuleSources` seems to imply a boolean value is required, however the description suggests a list of string(?)

It is also unclear how we can specify values for resolution; what is the format of the (I presume) string to achieve the best chance of link resolution. Could an example be provided in the README?

| Option                  | Default | Description                                                                                |
| ----------------------- | ------- | ------------------------------------------------------------------------------------------ |
| resolveUtilityTypes     | `true`  | Resolve links to `Partial`, `Omit`, etc. to their documentation on the TypeScript website. |
| additionalModuleSources | `false` | Specify additional node_modules to attempt to resolve links to MDN from.                   |

**Comment by Gerrit0** [comment]
I've just updated the readme to hopefully provide some more clarity:

> -   `additionalModuleSources`
>
>    Defaults to `[]`. Specifies additional node_modules packages to attempt to
    resolve links to MDN from. By default, resolves types declared in the
    `typescript`, `@types/web`, and `@webgpu/types` packages. You should only
    need to set this option if using an unusual type package to define globally
    available types.
