### ISSUE TITLE
Add support for linking to members

### ISSUE THREAD

**Issue by KDean-Dolphin** [Gerrit0/typedoc-plugin-mdn-links#22]
I have the typedoc-plugin-mdn-links installed, and I would like for it to support linking to members. Basically:

`@link Iterator | This works}`

`{@link Iterator#from | This doesn't work}`

`{@link Iterator#from() | This doesn't work}`

`{@link Iterator.from | This doesn't work}`

`{@link Iterator.from() | This doesn't work}`

The ones that don't work should go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/from.

Thanks.

**Comment by Gerrit0** [comment]
Hmm... lib.esnext.iterator.d.ts isn't a simple file, so breaks assumptions made here.

**Comment by Gerrit0** [comment]
> `{@link Iterator#from | This doesn't work}`
> `{@link Iterator#from() | This doesn't work}`

This isn't valid because `from` is a static method, not an instance method

> {@link Iterator.from() | This doesn't work}

This isn't valid because links are not function calls, and do not include parenthesis.

> {@link Iterator.from() | This doesn't work}

This works in 4.0
